In [1]:
import numpy as np
from pandas import DataFrame

In [2]:
np.random.seed(12345)
#乱数をどこから発生させるかを決める/同じ乱数列を得ることができる

In [6]:
dframe =DataFrame(np.random.randn(1000,4))

In [7]:
dframe.head()

          0         1         2         3
0 -1.166530 -0.075264  0.112345  0.166874
1  0.012628  0.815313 -0.732001  0.868791
2  0.149693  0.485218  0.161056 -1.068808
3  1.190359 -1.053204  0.776001  1.311260
4  1.159677  0.477395 -0.004493  0.574631

In [9]:
dframe.tail()

            0         1         2         3
995 -1.530608  0.058991 -0.337120  1.129394
996 -0.151214 -0.898121 -1.467595 -1.086964
997 -0.104017  1.442214 -1.713617  0.936543
998  1.932427  0.530258 -0.217213  0.988951
999  0.193746 -1.744483  0.761804 -1.544201

In [10]:
dframe.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.039859    -0.033350    -0.011749    -0.031858
std       1.004647     0.998154     0.987471     1.013590
min      -3.530912    -3.024110    -3.170292    -3.105636
25%      -0.738643    -0.698731    -0.692887    -0.758010
50%       0.011608    -0.016171     0.022570    -0.035527
75%       0.663800     0.605952     0.666451     0.693491
max       2.916153     3.061029     2.623689     3.144389

In [11]:
col =dframe[0]

In [12]:
col.head()

0   -1.166530
1    0.012628
2    0.149693
3    1.190359
4    1.159677
Name: 0, dtype: float64

In [13]:
col[np.abs(col)>3]

421   -3.530912
Name: 0, dtype: float64

In [14]:
np.abs(dframe)>3
#abs=絶対値

         0      1      2      3
0    False  False  False  False
1    False  False  False  False
2    False  False  False  False
3    False  False  False  False
4    False  False  False  False
5    False  False  False  False
6    False  False  False  False
7    False  False  False  False
8    False  False  False  False
9    False  False  False  False
10   False  False  False  False
11   False  False  False  False
12   False  False  False  False
13   False  False  False  False
14   False  False  False  False
15   False  False  False  False
16   False  False  False  False
17   False  False  False  False
18   False  False  False  False
19   False  False  False  False
20   False  False  False  False
21   False  False  False  False
22   False  False  False  False
23   False  False  False  False
24   False  False  False  False
25   False  False  False  False
26   False  False  False  False
27   False  False  False  False
28   False  False  False  False
29   False  False  False  False
..     ...    ...    ...    ...
970  False  False  False  False
971  False  False  False  False
972  False  False  False  False
973  False  False  False  False
974  False  False  False  False
975  False  False  False  False
976  False  False  False  False
977  False  False  False  False
978  False  False  False  False
979  False  False  False  False
980  False  False  False  False
981  False  False  False  False
982  False  False  False  False
983  False  False  False  False
984  False  False  False  False
985  False  False  False  False
986  False  False  False  False
987  False  False  False  False
988  False  False  False  False
989  False  False  False  False
990  False  False  False  False
991  False  False  False  False
992  False  False  False  False
993  False  False  False  False
994  False  False  False  False
995  False  False  False  False
996  False  False  False  False
997  False  False  False  False
998  False  False  False  False
999  False  False  False  False

[1000 rows x 4 columns]

In [15]:
dframe[(np.abs(dframe)>3).any(1)]
#any=どれかにTrue

            0         1         2         3
158  0.623798 -0.436479  0.901529 -3.044612
192  0.617561 -1.148738 -3.170292 -1.017073
348  0.813014 -1.202724 -0.286215 -3.105636
360  0.123291 -3.024110 -1.168413 -0.888664
421 -3.530912 -0.576175 -0.750648  0.025443
712 -0.928871  3.061029 -0.297909  0.990886
787  0.836054 -0.780620  0.622791  3.144389

In [17]:
np.sign(dframe)

       0    1    2    3
0   -1.0 -1.0  1.0  1.0
1    1.0  1.0 -1.0  1.0
2    1.0  1.0  1.0 -1.0
3    1.0 -1.0  1.0  1.0
4    1.0  1.0 -1.0  1.0
5    1.0  1.0  1.0 -1.0
6   -1.0 -1.0 -1.0 -1.0
7   -1.0  1.0 -1.0 -1.0
8    1.0 -1.0  1.0 -1.0
9    1.0 -1.0  1.0 -1.0
10   1.0 -1.0  1.0 -1.0
11   1.0 -1.0 -1.0 -1.0
12   1.0 -1.0 -1.0 -1.0
13   1.0 -1.0 -1.0  1.0
14  -1.0 -1.0  1.0 -1.0
15  -1.0 -1.0 -1.0 -1.0
16   1.0  1.0  1.0  1.0
17  -1.0 -1.0  1.0  1.0
18   1.0  1.0 -1.0 -1.0
19   1.0  1.0  1.0  1.0
20  -1.0 -1.0 -1.0 -1.0
21   1.0 -1.0 -1.0 -1.0
22   1.0  1.0 -1.0 -1.0
23  -1.0  1.0  1.0  1.0
24   1.0 -1.0  1.0 -1.0
25   1.0  1.0  1.0 -1.0
26   1.0 -1.0  1.0  1.0
27   1.0  1.0 -1.0 -1.0
28  -1.0 -1.0 -1.0 -1.0
29   1.0  1.0 -1.0 -1.0
..   ...  ...  ...  ...
970 -1.0 -1.0 -1.0 -1.0
971  1.0 -1.0  1.0  1.0
972 -1.0 -1.0 -1.0  1.0
973 -1.0 -1.0  1.0 -1.0
974 -1.0 -1.0  1.0  1.0
975 -1.0 -1.0 -1.0 -1.0
976 -1.0 -1.0 -1.0  1.0
977 -1.0 -1.0  1.0  1.0
978  1.0 -1.0 -1.0  1.0
979 -1.0 -1.0 -1.0  1.0
980  1.0 -1.0 -1.0  1.0
981  1.0 -1.0 -1.0  1.0
982 -1.0  1.0 -1.0  1.0
983 -1.0 -1.0  1.0 -1.0
984  1.0 -1.0 -1.0  1.0
985  1.0  1.0 -1.0  1.0
986  1.0  1.0 -1.0 -1.0
987  1.0  1.0 -1.0  1.0
988 -1.0  1.0  1.0 -1.0
989  1.0 -1.0 -1.0 -1.0
990  1.0 -1.0 -1.0 -1.0
991  1.0 -1.0 -1.0  1.0
992 -1.0  1.0 -1.0  1.0
993 -1.0 -1.0  1.0  1.0
994 -1.0 -1.0  1.0  1.0
995 -1.0  1.0 -1.0  1.0
996 -1.0 -1.0 -1.0 -1.0
997 -1.0  1.0 -1.0  1.0
998  1.0  1.0 -1.0  1.0
999  1.0 -1.0  1.0 -1.0

[1000 rows x 4 columns]

In [18]:
dframe[np.abs(dframe)>3]=np.sign(dframe)*3

In [20]:
dframe.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.039328    -0.033386    -0.011579    -0.031852
std       1.002939     0.997895     0.986940     1.012700
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.738643    -0.698731    -0.692887    -0.758010
50%       0.011608    -0.016171     0.022570    -0.035527
75%       0.663800     0.605952     0.666451     0.693491
max       2.916153     3.000000     2.623689     3.000000